### ISSUE TITLE
Support for more complex flags object

### ISSUE THREAD

**Issue by r-inaldi** [sergiodxa/flagged#17]
First of all, I like how simple the lib is also keeping it useful. 👍 

My question is, do you have any plans to support more complex flags object?
I have an [example](https://github.com/garbles/flag#motivation).

I know I could use this example, but I don't need everything from that lib.

Let me know, I can open a PR for this.

**Comment by r-inaldi** [comment]
What I mean is the nested objects. Not the computed flags.

**Comment by sergiodxa** [comment]
Hi @r-inaldi 

I have no plans to add more complex flags object, so far I haven't need it and reading the example I'm not sure it's a good practice, aside of helping organizing similar flags.

However I could make it easy for you to add that support yourself, I'm planning adding a `useFeatures` hook which will return the whole features object/array so you could make a custom `useFeature`, `Feature` or `withFeature` with support for nested objects.

**Comment by sergiodxa** [comment]
It was easier than I think to add nested flags support and to open useFeatures for external usage I still needed to add type support for nested flags so I directly added it.

**Comment by sergiodxa** [comment]
It's published in v1.1.0

**Comment by r-inaldi** [comment]
Thanks @sergiodxa 👍
