### ISSUE TITLE
Is the package transpiled?

### ISSUE THREAD

**Issue by RosenTomov** [sergiodxa/flagged#191]
### Additional Context
I've noticed that older browsers (e.g., previous version of the Edge browser with the Edge engine) get the following error `Object doesn’t support property  or method "fromEntries"`.

**Comment by sergiodxa** [comment]
It is, using TSDX, but I think the build tools is not adding poly fills, this way you can provide your own polyfill if you need it and you can avoid loading the polyfill if you don't need.

**Comment by RosenTomov** [comment]
Ok thanks for answering. The way we solved it in case anyone needs a polyfill:

- Import from corejs (works in Edge 18 and older, didn't work on older Chrome browsers);

- Import your own polyfill (worked everywhere)
```
if (!Object.fromEntries) {
  Object.fromEntries = function ObjectFromEntries(iter) {
    const obj = {};

    // eslint-disable-next-line no-restricted-syntax
    for (const pair of iter) {
      if (Object(pair) !== pair) {
        throw new TypeError('iterable for fromEntries should yield objects');
      }

      // Consistency with Map: contract is that entry has "0" and "1" keys, not
      // that it is an array or iterable.

      const { 0: key, 1: val } = pair;

      Object.defineProperty(obj, key, {
        configurable: true,
        enumerable: true,
        writable: true,
        value: val,
      });
    }

    return obj;
  };
}
```
