### ISSUE TITLE
How to get the list of features on a Class Component?

### ISSUE THREAD

**Issue by mrmello** [sergiodxa/flagged#252]
### Additional Context

Let's say I have a react js Class Component and want to get access to the list of features that were passed to `<FlagsProvider />`. How can I achieve that?
The `useFeatures()` hook gives me what I want but we can't use hooks in Class Components.

Let me know if it is clear.
Congrats on the library, very nice!

**Comment by sergiodxa** [comment]
You will need to create a HOC and call useFeatures there, then pass the list to the wrapped component.
```js
function withFeatures(Component) {
  return props => {
    const features = useFeatures()
    return <Component {...props} features={features} />
  }
}
```
Something like this.
