### ISSUE TITLE
Display a fallback when the feature is not enabled

### ISSUE THREAD

**Issue by Metalefs** [sergiodxa/flagged#321]
## Introduction:
Hello! Thank you for sharing your project, it's great! I just have a suggestion to display the fallback case from a function like 'render'. 

## Case:
The writing of a 'renderFallback' prop:  
A function to execute in case the call to '**useFeature(name: string)**' returns false inside the '**Feature**' component.

### E.g: 
  
 - flagged/src/index.tsx
  `export function Feature`
 

```diff
 (...)
 const hasFeature = useFeature(name);
+ if (!hasFeature && typeof renderFallback === 'function') return renderFallback();
 if (typeof render === 'function') return render(hasFeature);
 return render;
````

## Sugestion:
We would implement an optional renderFallback prop with null starting value here:

### flagged/src/index.tsx

```diff
export function Feature({
  name,
  children,
  render = children,
+ renderFallback = null
}:{
  name: string;
  children?:
    | React.ReactNode
    | ((hasFeature: boolean | FeatureGroup) => JSX.Element);
  render?:
    | React.ReactNode
    | ((hasFeature: boolean | FeatureGroup) => JSX.Element);
+ renderFallback?:
+   | React.ReactNode
+   | (() => JSX.Element);
}) 
```
then return the renderFallback function value after validating **hasFeature** here:

```diff
  const hasFeature = useFeature(name);
+if (!hasFeature && typeof renderFallback === 'function') return renderFallback();
  if (typeof render === 'function') return render(hasFeature);
  return render;
````

## flagged/example/src/index.js

```diff
+ {/* Render and Fallback Prop */}
+ <Feature name="v3" render={<V3Component />} renderFallback={<p>You are not in V3.</p>} />
```

Thanks for reading.

**Comment by Metalefs** [comment]
I created a pull-request with the changes
#322

**Comment by sergiodxa** [comment]
You can do this right now by passing a function to the `render` or `children` prop.

With children:
```tsx
import * as React from 'react';
import { Feature } from 'flagged';

function Header() {
  return (
    <header>
      <Feature name="v2">
        {(isEnabled: boolean) =>
          isEnabled ? <h1>My App v2</h1> : <h1>My App v1</h1>
        }
      </Feature>
    </header>
  );
}

export default Header;
```

With render prop:
```tsx
import * as React from 'react';
import { Feature } from 'flagged';

function Header() {
  return (
    <header>
      <Feature
        name="v2"
        render={(isEnabled: boolean) =>
          isEnabled ? <h1>My App v2</h1> : <h1>My App v1</h1>
        }
      />
    </header>
  );
}

export default Header;
```

**Comment by Metalefs** [comment]
> You can do this right now by passing a function to the `render` or `children` prop.

Yes, thanks for the response.
I want to reduce this sintax.

```jsx
render={(isEnabled: boolean) =>
   isEnabled ? <h1>My App v2</h1> : <h1>My App v1</h1>
 }
```
basically by already knowing the result (false)

**Comment by Metalefs** [comment]
> basically by already knowing the result (false)

To write it like this
```jsx
<header>
      <Feature
        name="v2"
        render={<h1>My App v2</h1>}
        renderFallback="{<h1>My App v1</h1>}
      />
</header>
```
It looks cleaner in my opinion

**Comment by sergiodxa** [comment]
You could create a local wrapper that receives the render and fallback, and render the Feature componente internally with a function to check the Boolean.

Because the API is really simple it’s quite easy to wrap it in a more complex and custom one, without making the code here more complex.
