### ISSUE TITLE
Validate multiple feature names at once

### ISSUE THREAD

**Issue by Metalefs** [sergiodxa/flagged#324]
Hello there! 
how can I validate multiple feature names with the Feature component?

Basically I want to do this:

```html
<Feature names={[feature1, feature2]}>
</Feature>
```

To enable the render only if all features are enabled

**Comment by sergiodxa** [comment]
You can nest the Feature component:
```js
<Feature name=“feature1”>
  <Feature name=“feature2”>
    code here
  </Feature>
</Feature>
```

**Comment by Metalefs** [comment]
thanks!

**Comment by rickysullivan** [comment]
Is there a limit to how many levels can be nested?

**Comment by sergiodxa** [comment]
@rickysullivan there’s no limit
