### ISSUE TITLE
Request to support feature disabled for Wrapper Component Feature

### ISSUE THREAD

**Issue by kbrueckner** [sergiodxa/flagged#428]
I'd like to have an option to use the Feature wrapper component for elements when a feature is disabled. That would help to easier build alternative route when features are not enabled.

Possible solution example might be:

```javascript
<FlagsProvider features={{ myFlag: true }}>
    <Feature name="myFlag">
        // feature enabled render part
    </Feature>
    <Feature name="myFlag" disabled>
        // feature disabled render part
    </Feature>
</FlagsProvider>
```

Another idea could be a different Wrapper like NotFeature:

```javascript
<FlagsProvider features={{ myFlag: true }}>
    <Feature name="myFlag">
        // feature enabled render part
    </Feature>
    <NotFeature name="myFlag">
        // feature disabled render part
    </NotFeature>
</FlagsProvider>
```

PS: I see that there is the option to go via the render attribute on Feature but the above requested solutions would pay in as convenience options.

**Comment by sergiodxa** [comment]
This could be built easily on top the current components.

```ts
import { useFeature } from "flagged";

type Props = {
  children: React.ReactNode;
  name: string;
  disabled?: boolean;
};

function Feature({ children, name, disabled = false }: Props) {
  let isEnabled = useFeature(name)
  if (disabled && !isEnabled) return null;
  return <>{children}</>
}
```

Because it's easier to build on user-land I would prefer to keep it outside the core.
