### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by ianchanning** [sergiodxa/flagged#534]
### Current Behavior

This throws an error with React 18.2.0:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (react.development.js:1476:1)
    at useContext (react.development.js:1484:1)
    at useFeatures (flagged.esm.js:44:20)
    at FlagsProvider (flagged.esm.js:37:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    ...
```
This is the code I have for `dist/flagged.esm` lines 33-45:

```js
function FlagsProvider(_ref) {
  var _ref$features = _ref.features,
      features = _ref$features === void 0 ? {} : _ref$features,
      children = _ref.children;
  var currentFeatures = useFeatures();
  return createElement(FeatureFlagsContext.Provider, {
    value: mergeFeatures(transformFlags(currentFeatures), transformFlags(features))
  }, children);
} // Custom Hook API

function useFeatures() {
  return useContext(FeatureFlagsContext);
} // Custom Hook API
```

### Expected Behavior

No error. I had no error with React 17.0.2.

### Suggested Solution(s)

After upgrading to React 18, the Auth0 Provider for v1.1.12 also gave the same error. Upgrading that to v2 fixed the error. So if you look at the https://github.com/auth0/auth0-react library provider changes between v1 and v2 that might give an idea for a fix.

### Your Environment

| Software | Version |
| -------- | ------- |
| Flagged  |     2.0.9    |
| React    |      18.2.0   |
| Browser  |    FF v116     |
| npm/yarn |     8.19.4    |

**Comment by sergiodxa** [comment]
I can't replicate it, [here's a CodeSandbox](https://codesandbox.io/s/flagged-example-72sk48) using latest Flagged version with React 18.2.0.

The source code doesn't call any hook conditionally or in a loop too, so I think most likely something in your bundler is causing you to have two different versions of React for some reason.

**Comment by ianchanning** [comment]
Yeah - its possibly something to do with my repo. My guess is that its Turbo Repo that's linking between libraries.

**Comment by ianchanning** [comment]
In the end it took deleting the `package-lock.json` and the `node_modules`, then it worked correctly. Otherwise if running `npm ls react` multiple modules were stuck on react 17.
